### ISSUE TITLE
How to compile alt-f-next for a DNS-325 ?

### ISSUE THREAD

**Issue by lecocqe** [awanga/alt-f-next#11]
Hello,

i'am a newbee in linux and i own a dns-325, i want to compile alt-f-next for it. How do i do this the best way ?

which options in "menuconfig" ?
because i tried to compile with alt-f installed on it but it misses ncusrses lib ? 

thank you in advance,

Eric

**Comment by ser0ja** [comment]
Hi, also ask for help with compiling the firmware.

**Comment by Black6spdZ** [comment]
anyone have a working build env setup?

**Comment by lecocqe** [comment]
i found what i need. i just didn't look at the correct place.
