### ISSUE TITLE
USELESS

### ISSUE THREAD

**Issue by Black6spdZ** [awanga/alt-f-next#13]
firmware for NAS is ALL but useless as a NETWORK ATTACHED STORAGE device! You would think that at the very least the functionality would be baked in to have this as a usable NETWORK STORAGE DEVICE out of the box without installing 10 packages and dependencies.. very frustrated.  Way to make an old device pretty much useless! Not to mention when you do manage to get Samba installed defaults still insist on having SMB1 protocol.. guess the memo was lost that that has been disabled out of most modern OS for years prior to the building of this firmware

**Comment by awanga** [comment]
Don't have time to respond fully to this. alt-f-next helped me get some extra use out of my NAS. Shared it to hopefully help some others too. If you need something that "just works" feel free to buy some new and more capable hardware.
