### ISSUE TITLE
installed Alt-f for DNS-325, but refuses to install alt-f packages

### ISSUE THREAD

**Issue by lecocqe** [awanga/alt-f-next#14]
Hello,

i just installed latest alt-f for my DNS-325. i'm trying to install alt-f packages but:
![image](https://user-images.githubusercontent.com/18657222/202758701-e81b74e2-b0a7-4852-a966-70941975f6d0.png)

do you have an idea ?

best regards,

Eric

**Comment by lowgik** [comment]
same here, i disabled https://github.com/awanga/alt-f-next_binaries/raw/pkgs/stable/
and installed ipkg from https://downloads.sourceforge.net/project/alt-f/pkgs/stable

**Comment by awanga** [comment]
Seems like there was a change in how to access raw packages from GitHub in the last few years. Try changing the URL to https://raw.githubusercontent.com/awanga/alt-f-next_binaries/pkgs/stable/ instead.
