### ISSUE TITLE
boot buid dns-320 (dev) fail

### ISSUE THREAD

**Issue by gpancot** [awanga/alt-f-next#2]
Hi all,

thank you very much for your wonderful work.
i am trying to boot via tftp  last build (dev).
It fail with:

VFS: Mounted root (squashfs filesystem) readonly on device 1:0.
devtmpfs: error mounting -2
Freeing unused kernel memory: 1024K
Run /init as init process
pre-init started, pid=1
mount: mounting proc on /proc failed: No such file or directory
grep: /proc/cmdline: No such file or directory
grep: /proc/cmdline: No such file or directory
grep: /proc/filesystems: No such file or directory
pre-init: no-aufs
grep: /proc/filesystems: No such file or directory
umount: can't unmount /proc: No such file or directory
mount: mounting proc on /proc failed: No such file or directory
mount: can't read '/proc/mounts': No such file or directory
mount: mounting sysfs on /sys failed: No such file or directory
mount: mounting tmpfs on /tmp failed: No such file or directory
mkdir: can't create directory '/dev/': Read-only file system
mount: mounting devpts on /dev/pts failed: No such file or directory
/etc/init.d/rcS: line 19: can't create /dev/null: nonexistent directory
/etc/init.d/rcS: line 0: can't open '/dev/null': No such file or directory
mkdir: can't create directory '/tmp/': Read-only file system
ln: /var/lib: Read-only file system
mkdir: can't create directory '/tmp/': Read-only file system
ln: /var/run: Read-only file system
mkdir: can't create directory '/tmp/': Read-only file system
ln: /var/log: Read-only file system
mkdir: can't create directory '/tmp/': Read-only file system
ln: /var/cache: Read-only file system
mkdir: can't create directory '/tmp/': Read-only file system
ln: /var/spool: Read-only file system
mkdir: can't create directory '/tmp/': Read-only file system
ln: /var/db: Read-only file system
mkdir: can't create directory '/tmp/': Read-only file system
ln: /var/lock: Read-only file system
mkdir: can't create directory '/mnt': Read-only file system
mkdir: can't create directory '/var/spool/': Read-only file system
mkdir: can't create directory '/var/spool/': Read-only file system
mkdir: can't create directory '/var/run/': Read-only file system
chmod: /var/spool/lpd: No such file or directory
chmod: /var/spool/samba: No such file or directory
/etc/init.d/rcS: line 29: can't create /etc/bay: Read-only file system
/etc/init.d/rcS: line 30: can't create /etc/printcap: Read-only file system
/etc/init.d/rcS: line 32: can't create /sys/kernel/mm/ksm/run: nonexistent directory
start-stop-daemon: can't open '/proc': No such file or directory
mkdir: can't create directory '/tmp/': Read-only file system
grep: /proc/cpuinfo: No such file or directory
grep: /proc/cpuinfo: No such file or directory
/etc/init.d/rcS: line 50: can't create /dev/null: nonexistent directory

kernel seems boot ok, something wrong with the initrd?

**Comment by gpancot** [comment]
boot  complete after adding some dir in "board/dns32x/customroot/":

$ ls -l board/dns32x/customroot/
drwxrwxr-x  3 1002 1002 4096 set 12 17:53 dev
drwxrwxr-x 16 1002 1002 4096 set 12 00:57 etc
-rwxrwxr-x  1 1002 1002 5443 set 12 00:58 init
drwxrwxr-x  3 1002 1002 4096 set 12 17:53 newroot
drwxrwxr-x  2 1002 1002 4096 set 12 17:53 proc
drwxrwxr-x  2 1002 1002 4096 set 12 00:57 root
drwxrwxr-x  4 1002 1002 4096 set 12 17:53 rootmnt
drwxrwxr-x  2 1002 1002 4096 set 12 00:57 sbin
drwxrwxr-x  2 1002 1002 4096 set 12 17:53 sys
drwxrwxr-x  5 1002 1002 4096 set 12 17:53 tmp
drwxrwxr-x  7 1002 1002 4096 set 12 00:57 usr
drwxrwxr-x  2 1002 1002 4096 set 12 17:53 var

**Comment by awanga** [comment]
Yeah, that's embarrassing... I had those folders in my repo, but git doesn't add empty folders, so I assumed they were added when they were not. As a (better?) alternative, I added a line to the configfs script to add the mount points programmatically. The relevant commit is in the dev branch now (f81717cf).
