### ISSUE TITLE
Not an issue, more a question.

### ISSUE THREAD

**Issue by lopirata** [awanga/alt-f-next#7]
Is there any forum/group that discuss alt-f-next?
Can't find any.
Another question: It's OK to install https://github.com/awanga/alt-f-next/releases/tag/stable files?
Used Try It! on DNS-321 and didn't work.

**Comment by realbsb** [comment]
I'll just add one more question: to upgrade from Alt-F 1.0, can I limit myself to just uploading a bin file to System/Firmware?

**Comment by awanga** [comment]
I don't think there is an active place to discuss it. Seems like there's more interest in this old NAS than I expected. Maybe I'll open discussion on this repo, just don't have much time to facilitate.

The stable release up now should be okay (worked for me, but I only tested on DNS-323, so your mileage may vary).
